### ISSUE TITLE
Página en blanco en el step=base_de_datos

### ISSUE THREAD

**Issue by NESTicle** [PHPostReboot/PHPost#4]
**Descripción del Bug**
Llenando la información del siguiente formulario:
![image](https://user-images.githubusercontent.com/1715022/133520176-2c2b3a87-a154-47ff-9e8c-7c073bfc494c.png)

Si la base de datos no se encuentra creada sale en blanco la página:

**Cómo reproducir el bug**
1. Iniciar el instalador
2. Aceptar acuerdo de licencia
3. Continuar en la sección de Permisos de escritura
4. Llenar el formulario y en la base de datos agregar una db que no se haya creado en mysql

**Comportamiento esperado**
Visualizar un error: "La base de datos no existe" o algo así

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/1715022/133525159-1fedc366-7e11-42fa-8ad3-135a71c3ee40.png)

**PC:**
 - OS: Windows
 - Navegador: Vivaldi y Microsoft Edge

**Comment by joelmiguelvalente** [comment]
Volverá a la misma pantalla, pero lo que cambiará es el titulo y dará un mensaje!
